### ISSUE TITLE
Access denied error

### ISSUE THREAD

**Issue by amit1295** [aws-samples/ec2-flexibility-score-dashboard#1]
Hi guys,

When deploying the tool as instructed, everything is deploying seamlessly.

Unfortunately, when we are moving to the Cloudwatch Dashboard we are getting access denied problem.
After adding to all the functions role Admin privileged just for the sake of testing, the problem continues( Screenshot attached).

![Screenshot 2023-11-12 at 5 52 55](https://github.com/aws-samples/ec2-flexibility-score-dashboard/assets/65691031/b8a61fee-b0f0-4d61-9ba8-6d6030724293)

Could you kindly advise us on this matter? 

Thanks

**Comment by bpguasch** [comment]
Hello @amit1295, 

The Lambda function that performs the calculations assumes the IAM Role arn:aws:iam::Account_ID:role/ParamOrgRoleName where "ParamOrgRoleName" is the IAM Role name that you specify as a CDK parameter when you deploy the project.

In order for all the operations to work, is that IAM Role that needs to have the required permissions. You can check all the required permissions here https://github.com/aws-samples/ec2-flexibility-score-dashboard#using-the-tool 😄
